sonar.projectKey=car-rental-app
sonar.sources=src/app
sonar.tests=src/app

# Exclude test files from sources
sonar.exclusions=**/*.spec.ts

# Include only test files
sonar.test.inclusions=**/*.spec.ts

# Coverage path
sonar.javascript.lcov.reportPaths=coverage/car-rental/lcov.infoc

# THIS IS THE MOST IMPORTANT LINE
sonar.javascript.lcov.reportPaths=coverage/car-rental/lcov.info

# Optional but recommended
sonar.sourceEncoding=UTF-8